name: Train scikit-learn model

on:
  push:
    paths:
      - "src/**"
      - "requirements.txt"
      - ".github/workflows/train.yml"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_PROJECT: mlops-pycon-2023

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: |
          python src/models/train_sklearn.py --n_estimators 300 --test_size 0.2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: artifacts/
