# testing
name: Entrenar modelo experiencias (scikit-learn)

on:
  push:
    paths:
      - "src/**"
      - "requirements.txt"
      - ".github/workflows/train.yml"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      # 👇 Configura estos en Settings → Secrets and variables → Actions
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_PROJECT: mlops-pycon-2023
      WANDB_ENTITY: ${{ vars.WANDB_ENTITY }}  # o usa secrets.WANDB_ENTITY si prefieres

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training (experiencias)
        run: |
          python src/models/train_sklearn.py \
            --n_estimators 300 \
            --test_size 0.2 \
            --log_steps 50 100 200 300

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: experiencias-model-artifacts
          path: artifacts/
